# Class ResourceTimeTable
import sys
import xlrd
import xlwt


from . import slot
from . import parameters
from . import net_ap
from . import net_link

from . import net_graph
from . import task

class ResourceTimeTable:
    def __init__(self, slotSize, slotNum, currentTime):
        self._slotSize = slotSize
        self._rscNum = 0
        self._slotNum = slotNum
        # rsc2SlotRowDict, its key is generated by link's or server's getKey() method, its value is a list of Slot objects
        self._rsc2SlotRowDict = {}
        # slotStartTime is the time of the first slot in slot row.
        self._slotStartTime = 0
        # The end of the slot row, is the furthest allocated slot index or the current slot index. 
        self._rsc2SloRowEnds = {}
        self._currentTime = currentTime
        self._taskAlcLinkInfoDict = {}
        self._taskAlcSerInfoDict = {}

    def addLinkRsc(self, link):
        tmpRow = []
        print("In addLinkRsc, bandwidth:%d" % (link.getBandwidth()))
        for i in range(self._slotNum):
            tmpRow.append(slot.Slot(parameters.CODE_RSC_LINK, link.getBandwidth()))
        self._rscNum = self._rscNum + 1
        self._rsc2SlotRowDict[link.getKey()] = tmpRow
        self._rsc2SloRowEnds[link.getKey()] = self._currentTime - self._slotStartTime

    def addServerRsc(self, server):
        tmpRow = []
        for i in range(self._slotNum):
            tmpRow.append(slot.Slot(parameters.CODE_RSC_SERVER, server.getRscAmount()))
        self._rsc2SlotRowDict[server.getKey()] = tmpRow
        self._rsc2SloRowEnds[server.getKey()] = self._currentTime - self._slotStartTime

    def allocateLinkSlot(self, task, time, path):
        if path.getPathLength() == 0:
            print("In resource_time_table, encounter a zero path.")
            return 0, 0, 0
        if time < self._currentTime:
            sys.exit("Argument 'time' is smaller than current time.")
        index, slotBan = self.__searchAvailableLinkSlot(time - self._slotStartTime, path)
        
        # Try to insert the index of link slot for this task,
        # if failed, then creat a index list for this task
        try:
            self._taskAlcLinkInfoDict[task.getKey()].append(index)
        except KeyError:
            print("In resource_time_table, create a taskAlcLinkInfo for %s." % (task.getKey()))
            self._taskAlcLinkInfoDict[task.getKey()] = [index]
        
        linkLenList = path.getLinkLengthList()
        path.reset()
        # Allocate slots of links in path for this task.
        tmpIndex = index
        for i in range(len(linkLenList)):
            linkKey = path.nextLink().getKey()
            # Add task into corresponding link slot.
            self._rsc2SlotRowDict[linkKey][tmpIndex].addTask(task, slotBan)
            # Update slot row end
            self.__updateSlotRowEnd(linkKey, tmpIndex + self._slotStartTime)

            tmpIndex = tmpIndex + linkLenList[i]
        # Return time of allocated slot and allocated bandwidth.
        startTime = index + self._slotStartTime
        endTime = tmpIndex + self._slotStartTime + 1
        return startTime, endTime, slotBan

    def allocateServerSlot(self, task, time, server):
        if time < self._currentTime:
            sys.exit("Argument 'time' is smaller than current time.")
        index  = self.__searchAvailableServerSlot(time - self._slotStartTime, server)

        # Try to insert the index of server slot for this task,
        # if failed, then creat a index list for this task.
        try:
            self._taskAlcSerInfoDict[task.getKey()].append(index)
        except KeyError:
            self._taskAlcSerInfoDict[task.getKey()] = [index]
            print("In resource_time_table, create a taskAlcSerInfo for %s." % (task.getKey()))
        print("Allocate %s's slot %d for %s." % (server.getKey(), index, task.getKey()))
        # print("taskAlcSerInfo:", self._taskAlcSerInfoDict[task.getKey()])
        self._rsc2SlotRowDict[server.getKey()][index].addTask(task, 1)
        # self.printStatus()
        # print("%s's slot %s, status:" % (server.getKey(),index),self._rsc2SlotRowDict[server.getKey()][index].getStatus())
        # Return time of allocated slot
        startTime = index + self._slotStartTime
        endTime = startTime + 1
        return startTime, endTime       

    def freeRscFromCurrentTime(self):
        currentIndex = self._currentTime - self._slotStartTime
        for k in list(self._rsc2SlotRowDict.keys()):
            for i in range(self._rsc2SloRowEnds[k] - currentIndex):
                self._rsc2SlotRowDict[k][currentIndex + i].free()

    def recallRsc(self, time, task, path):
        linkLenList = path.getLinkLengthList()
        print("In resource_time_table, recall resources of %s" %(task.getKey()))
        
        # Free server slot resource.
        try:
            print("taskAlcSerInfo for %s" % (task.getKey()))
            print( self._taskAlcSerInfoDict[task.getKey()])
            for index in self._taskAlcSerInfoDict[task.getKey()]:
                if time - self._slotStartTime > index:
                    continue
                elif self._rsc2SlotRowDict[task.getDispatchedServer().getKey()][index].deleteTask(task) != True:
                    sys.exit("In resource_time_table, no %s in this server slot, index:%d." % (task.getKey(), index))
                print("Free server rsc at index %d for %s" % (index, task.getKey()))
            # dump stale information
            for i in range(len(self._taskAlcSerInfoDict[task.getKey()])):
                if time  > self._taskAlcSerInfoDict[task.getKey()][i] + self._slotStartTime:
                    continue
                else:
                    self._taskAlcSerInfoDict[task.getKey()] = self._taskAlcSerInfoDict[task.getKey()][0:i]
                    break
        except KeyError:
            print("%s has no server resource to recall" % (task.getKey()))
        # Free link slot resource.
        try:
            print("taskAlcLinkInfo for %s" % (task.getKey()))
            print( self._taskAlcLinkInfoDict[task.getKey()])
            for index in self._taskAlcLinkInfoDict[task.getKey()]:
                tmpIndex = index
                path.reset()
                for length in linkLenList:
                    if index + self._slotStartTime < time:
                        print("History should be reserved.")
                        continue
                    elif self._rsc2SlotRowDict[path.nextLink().getKey()][tmpIndex].deleteTask(task) != True:
                        sys.exit("In resource_time_table, no %s in this link slot, index:%d." % (task.getKey(), index))
                    print("Free link rsc at index %d for %s" % (index, task.getKey()))
                    tmpIndex = tmpIndex + length
            # dump stale information
            for i in range(len(self._taskAlcLinkInfoDict[task.getKey()])):
                if time  > self._taskAlcLinkInfoDict[task.getKey()][i] + self._slotStartTime:
                    continue
                else:
                    self._taskAlcLinkInfoDict[task.getKey()] = self._taskAlcLinkInfoDict[task.getKey()][0:i]
                    break
        except KeyError:
            print("%s has no server resource to recall" % (task.getKey()))
        
    def updateTime(self):
        self._currentTime = self._currentTime + 1
        for k in list(self._rsc2SloRowEnds.keys()):
            self.__updateSlotRowEnd(k, self._currentTime)
    
    def __rscKey(self, rsc):
        if type(rsc) == net_ap.NetAP:
            return 'server-' + str(rsc.getID())
        elif type(rsc) == net_link.NetLink:
            return 'link-' + str(rsc.getID())

    def __checkPathBandwidth(self, index, path):
        distList = path.getLinkLengthList()
        path.reset()
        tmpLink = path.nextLink()
        minBan = self._rsc2SlotRowDict[tmpLink.getKey()][index].remainedRsc()
        # print("In resource_time_table.py, checkPathBandwidth:")
        # print("From %s to %s, remained bandwidth is:%d." % (tmpLink.getHeadAP().getKey(), tmpLink.getTailAP().getKey(), minBan))
        for i in range(len(distList)-1):
            tmpLink = path.nextLink()
            tmpBan = self._rsc2SlotRowDict[tmpLink.getKey()][index+distList[i]].remainedRsc()
            # print("From %s to %s, remained bandwidth is:%d." % (tmpLink.getHeadAP().getKey(), tmpLink.getTailAP().getKey(), tmpBan))
            # print(tmpBan)
            index = index + distList[i]
            if tmpBan < minBan:
                minBan = tmpBan
        print("In resource_time_table, minBan:%d" % minBan)
        return minBan
    
    def __searchAvailableLinkSlot(self, index, path):
        slotBan = 0
        while slotBan <= 0:
            slotBan = self.__checkPathBandwidth(index, path)
            index = index + 1
        return index-1, slotBan
    
    def __searchAvailableServerSlot(self, index, server):
        serverSlots = self._rsc2SlotRowDict[self.__rscKey(server)]
        while serverSlots[index].remainedRsc() <=0:
            index = index + 1
        return index

    def __updateSlotRowEnd(self, rscKey, time):
        if time - self._slotStartTime > self._rsc2SloRowEnds[rscKey]:
            self._rsc2SloRowEnds[rscKey] = time - self._slotStartTime

    def printStatus(self):
        keyList = list(self._rsc2SlotRowDict.keys())
        for index in range(25):
            status = str(index) + "---|"
            for key in keyList:
                status = status + self._rsc2SlotRowDict[key][index].getStatus() + "|"
            print(status)
        # for key in keyList:
        #     print(key," has %d slots." % (len(self._rsc2SlotRowDict[key])))
    
    def saveStatusIntoXlsSheet(self, targetSheet):
        keyList = list(self._rsc2SlotRowDict.keys())
        for i in range(len(keyList)):
            targetSheet.write(0, i, keyList[i])
        for index in range(self._slotNum):
            for ki in range(len(keyList)):
                targetSheet.write(index+1, ki, self._rsc2SlotRowDict[keyList[ki]][index].getStatus())
        

                



if __name__ == "__main__":
    ng = net_graph.createANetGraph()
    rtt = ResourceTimeTable(1, 100, 0)
    linkList = ng.getLinkList()
    serverList = ng.getServerList()
    for l in linkList:
        rtt.addLinkRsc(l)
    for s in serverList:
        rtt.addServerRsc(s)
    path1 = ng.getShortestPath(serverList[0], serverList[4])
    
    tmpTask = task.Task(parameters.CODE_TASK_TYPE_IoT, serverList[0], 20, 0, 5,4)
    tmpTask.setDispatchedServer(serverList[4])
    print("start_ap:%s, end_ap:%s." % (serverList[0].getKey(), serverList[4].getKey()))
    startTime, endTime, ban = rtt.allocateLinkSlot(tmpTask, time=0, path=path1)
    print("Data transmission, start_time:%d, end_time:%d, bandwidth:%d" % (startTime, endTime, ban))
    startTime, endTime = rtt.allocateServerSlot(tmpTask, endTime, tmpTask.getDispatchedServer())
    print("Computation, start_time:%d, end_time:%d." % (startTime, endTime))